# Generated by Django 4.2.20 on 2025-03-29 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ingredients",
            fields=[
                ("ingredient_id", models.AutoField(primary_key=True, serialize=False)),
                ("ingredient_name", models.CharField(max_length=100, unique=True)),
            ],
            options={"db_table": "Ingredients", "managed": True,},
        ),
        migrations.CreateModel(
            name="UserIngredients",
            fields=[
                (
                    "user_ingredient_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("expiration_date", models.DateField(blank=True, null=True)),
                (
                    "ingredient",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="ingredients.ingredients",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="users.users",
                    ),
                ),
            ],
            options={"db_table": "User_Ingredients", "managed": True,},
        ),
        migrations.CreateModel(
            name="ExcludedIngredients",
            fields=[
                ("excluded_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "ingredient",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="ingredients.ingredients",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="users.users",
                    ),
                ),
            ],
            options={"db_table": "Excluded_Ingredients", "managed": True,},
        ),
    ]
