# Generated by Django 4.2.20 on 2025-04-13 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ingredients", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(name="excludedingredients", options={},),
        migrations.AlterModelOptions(name="ingredients", options={},),
        migrations.AlterModelOptions(name="useringredients", options={},),
        migrations.RenameField(
            model_name="excludedingredients",
            old_name="ingredient",
            new_name="ingredient_id",
        ),
        migrations.RenameField(
            model_name="useringredients",
            old_name="ingredient",
            new_name="ingredient_id",
        ),
        migrations.AlterModelTable(name="excludedingredients", table=None,),
        migrations.AlterModelTable(name="ingredients", table=None,),
        migrations.AlterModelTable(name="useringredients", table=None,),
    ]
