# Generated by Django 4.2.20 on 2025-03-29 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Users",
            fields=[
                ("user_id", models.AutoField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=50, unique=True)),
                ("email", models.CharField(max_length=100, unique=True)),
                ("password", models.TextField()),
            ],
            options={"db_table": "Users", "managed": True,},
        ),
    ]
