# Generated by Django 4.2.20 on 2025-04-13 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_users_options_users_groups_users_is_active_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(name="users", table=None,),
    ]
