# Generated by Django 4.2.20 on 2025-04-13 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_users_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="expo_push_token",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
