# Generated by Django 4.2.20 on 2025-03-29 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
        ("recipes", "0008_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Likes",
            fields=[
                ("like_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "rcp_number",
                    models.ForeignKey(
                        blank=True,
                        db_column="rcp_number",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="recipes.recipes",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="users.users",
                    ),
                ),
            ],
            options={"db_table": "Likes", "managed": True,},
        ),
        migrations.CreateModel(
            name="Bookmarks",
            fields=[
                ("bookmark_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "rcp_number",
                    models.ForeignKey(
                        blank=True,
                        db_column="rcp_number",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="recipes.recipes",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="users.users",
                    ),
                ),
            ],
            options={"db_table": "Bookmarks", "managed": True,},
        ),
    ]
