# Generated by Django 4.2.20 on 2025-04-13 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("favorite", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(name="bookmarks", options={},),
        migrations.AlterModelOptions(name="likes", options={},),
        migrations.AlterModelTable(name="bookmarks", table=None,),
        migrations.AlterModelTable(name="likes", table=None,),
    ]
