# Generated by Django 4.2.20 on 2025-03-22 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0003_alter_recipe_info_car_alter_recipe_info_eng_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="rcp_nm",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="rcp_pat2",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="rcp_way2",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
