# Generated by Django 4.2.20 on 2025-03-22 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0004_alter_recipe_rcp_nm_alter_recipe_rcp_pat2_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ingredient",
            fields=[
                ("ingredient_id", models.AutoField(primary_key=True, serialize=False)),
                ("ingredient_name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("user_id", models.AutoField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=50, unique=True)),
                ("email", models.EmailField(max_length=100, unique=True)),
                ("password", models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name="recipe", name="rcp_nm", field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="rcp_pat2",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="rcp_way2",
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name="UserIngredient",
            fields=[
                (
                    "user_ingredient_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("expiration_date", models.DateField()),
                (
                    "ingredient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="recipes.ingredient",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="recipes.user"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ShoppingList",
            fields=[
                ("shopping_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "ingredient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="recipes.ingredient",
                    ),
                ),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="recipes.recipe"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="recipes.user"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RecipeStep",
            fields=[
                ("step_id", models.AutoField(primary_key=True, serialize=False)),
                ("step_order", models.IntegerField()),
                ("instruction", models.TextField()),
                ("image_url", models.TextField(blank=True, null=True)),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="recipes.recipe"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RecipeIngredient",
            fields=[
                (
                    "recipe_ingredient_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "ingredient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="recipes.ingredient",
                    ),
                ),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="recipes.recipe"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Like",
            fields=[
                ("like_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="recipes.recipe"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="recipes.user"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExcludedIngredient",
            fields=[
                ("excluded_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "ingredient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="recipes.ingredient",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="recipes.user"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Bookmark",
            fields=[
                ("bookmark_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="recipes.recipe"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="recipes.user"
                    ),
                ),
            ],
        ),
    ]
