# Generated by Django 4.2.20 on 2025-03-22 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0005_ingredient_user_alter_recipe_rcp_nm_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="excludedingredient", name="ingredient",),
        migrations.RemoveField(model_name="excludedingredient", name="user",),
        migrations.RemoveField(model_name="like", name="recipe",),
        migrations.RemoveField(model_name="like", name="user",),
        migrations.RemoveField(model_name="recipeingredient", name="ingredient",),
        migrations.RemoveField(model_name="recipeingredient", name="recipe",),
        migrations.RemoveField(model_name="recipestep", name="recipe",),
        migrations.RemoveField(model_name="shoppinglist", name="ingredient",),
        migrations.RemoveField(model_name="shoppinglist", name="recipe",),
        migrations.RemoveField(model_name="shoppinglist", name="user",),
        migrations.RemoveField(model_name="useringredient", name="ingredient",),
        migrations.RemoveField(model_name="useringredient", name="user",),
        migrations.AlterField(
            model_name="recipe",
            name="info_car",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="info_eng",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="info_fat",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="info_na",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="info_pro",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="info_wgt",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(name="Bookmark",),
        migrations.DeleteModel(name="ExcludedIngredient",),
        migrations.DeleteModel(name="Ingredient",),
        migrations.DeleteModel(name="Like",),
        migrations.DeleteModel(name="RecipeIngredient",),
        migrations.DeleteModel(name="RecipeStep",),
        migrations.DeleteModel(name="ShoppingList",),
        migrations.DeleteModel(name="User",),
        migrations.DeleteModel(name="UserIngredient",),
    ]
