# Generated by Django 4.2.20 on 2025-03-29 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0006_remove_excludedingredient_ingredient_and_more"),
    ]

    operations = [
        migrations.DeleteModel(name="Recipe",),
    ]
