# Generated by Django 4.2.20 on 2025-04-03 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0008_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipes",
            name="rcp_ingredient_cnt",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="recipes",
            name="rcp_laststep",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="recipes",
            name="rcp_cooktime",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
