# Generated by Django 4.2.20 on 2025-04-13 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0009_recipes_rcp_ingredient_cnt_recipes_rcp_laststep_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(name="recipes", options={},),
        migrations.AlterModelOptions(name="recipesingredients", options={},),
        migrations.AlterModelOptions(name="recipesteps", options={},),
        migrations.AlterModelTable(name="recipes", table=None,),
        migrations.AlterModelTable(name="recipesingredients", table=None,),
        migrations.AlterModelTable(name="recipesteps", table=None,),
    ]
