# Generated by Django 4.2.20 on 2025-04-13 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shopping", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(name="shoppinglist", options={},),
        migrations.RenameField(
            model_name="shoppinglist", old_name="ingredient", new_name="ingredient_id",
        ),
        migrations.AlterModelTable(name="shoppinglist", table=None,),
    ]
